### ISSUE TITLE
help needed 

### ISSUE THREAD

**Issue by naveen-git21** [rajveersinghcse/PetCare-AI-Chatbot#1]
since i am new to this language model i am unable to understand , how to run this project .
i have cloned this repository and installed the requirements but i am unable to understand this

You have to run your llama model from Ollama.
Ollama serve.
 
 i even installed ollama in my device . 
 i am running the commands in terminal but i dont know what to do for running llama.
 please help

**Comment by rajveersinghcse** [comment]
Hey, Hi Naveen,
Did you install the LLama3 model? If you didn't then use this command in the terminal.
Ollama pull llama3
