### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by Dmitrii173173** [rajveersinghcse/PetCare-AI-Chatbot#2]
I added to the requirements.txt:

pip install pypdf
pip install sentence-transformers
pip install -U langchain-huggingface

pip uninstall torch torchvision torchaudio -y
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118

install:  
ollama pull llama3

Everything's working fine. Thank you for your work.

**Comment by rajveersinghcse** [comment]
Thanks for your contribution 😊
